### ISSUE TITLE
Plugin Error on start Android Studio

### ISSUE THREAD

**Issue by vonmecheln** [typ0520/JsonToDartClass#1]
Plugin 'com.github.typ0520.jsontodart' failed to initialize and will be disabled.  Please restart Android Studio.

java.io.FileNotFoundException: /Users/tong/Desktop/idea.txt (Arquivo ou diretório inexistente)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at kotlin.io.FilesKt__FileReadWriteKt.appendBytes(FileReadWrite.kt:91)
    at kotlin.io.FilesKt__FileReadWriteKt.appendText(FileReadWrite.kt:118)
    at kotlin.io.FilesKt__FileReadWriteKt.appendText$default(FileReadWrite.kt:118)
    at wu.seal.jsontodart.utils.LogUtil.i(LogUtil.kt:19)
    at wu.seal.jsontodart.JsonToKotlinApplication.initComponent(JsonToKotlinApplication.kt:15)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:486)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:104)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$9(ApplicationImpl.java:447)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:471)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:88)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:405)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:391)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:217)
    at com.intellij.idea.IdeaApplication.lambda$initApplication$0(IdeaApplication.java:77)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
![Captura de tela de 2019-07-22 00-04-37](https://user-images.githubusercontent.com/318178/61603669-dedf2480-ac14-11e9-9465-385396077467.png)

**Comment by agubha** [comment]
same issue here... Any one else?

**Comment by typ0520** [comment]
Already fixed, you can download a new version

https://github.com/typ0520/JsonToDartClass/releases/tag/v1.0.8
